# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/tasks
Accept: application/json

###

POST http://127.0.0.1:8000/tasks/
Content-Type: application/json

{
    "title" : "test",
    "description": "Some fun test to see what's in the db",
  "status": "Pending"
}